import Topheader from "@/components/Topheader";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Mission from "@/components/Mission";
import Counter from "@/components/Counter";
import Slider from "@/components/Slider";
import Event from "@/components/Event";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>NAS-IT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topheader />
      <Navbar />
      <Slider />
      <Mission />
      <Counter />
      <Event />
      <Footer />
    </>
  );
}
